services:
  - type: web
    name: final-bot1-0
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: "7511704960:AAFKDWgg2-cAzRxywX1gXK47OQRWJi72qGw"
      - key: WEBHOOK_URL
        value: "https://final-bot1-0.onrender.com/webhook"
      - key: PORT
        value: "5000"
